name: CI - Build, Lint, Test

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install
      run: yarn install --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test:dist
      env:
        CI: true

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF#refs/heads/})"
      id: extract_branch

    - name: Extract task reference
      shell: bash
      run: echo "##[set-output name=task;]$(echo '${{ steps.extract_branch.outputs.branch }}' | grep -oE '[A-Za-z]+-[0-9]+' -)"
      id: extract_task

#    - name: Construct preid
#      shell: bash
#      run: echo "${{ steps.extract_task.outputs.branch }}" | grep -oE '[A-Za-z]+-[0-9]+' -
#      id: construct_preid

    - name: Set Registry Url
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'

    - name: Checkout branch (to prevent "Detached git HEAD, please checkout a branch to choose versions.")
      run: git checkout -b ${{ steps.extract_branch.outputs.branch }}

    - name: Publish
      run: lerna publish prerelease --no-git-tag-version --no-push --force-publish --dist-tag ${{ steps.extract_task.outputs.task }} --preid ${{ steps.extract_task.outputs.task }}-${GITHUB_SHA:0:8} --yes --no-verify-access --ignore-prepublish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
